tensorflow:
  gpu_memory_growth: true
voxel_fluid:
  tasks:
    boundary:
      type: classification
      labels:
      - interior
      - boundary
      outputs: 2
    normal:
      type: regression
      outputs: 3
  features:
    occupancy: 1
  approach: sparse_regionwise
  search_radius: 1.5
  grid_length: 0.1
  enable_plot: false
  coarse_prediction: null
prediction:
  batch_size: 100000
  device: cuda
  initial_step: -1
  final_step: -1
  skip_steps: 1
  grid_offset: false
  resolution_based_on_mean_distance: true
  hdp: 2.0
  extract_mesh: true
  model_path: /work1/Doutorado/data/3D/static/kfold3_hdp=2.0/sparse_regionwise_approach/models/model_sparse_voxelized_fluid_cnn_v3_4_10000_1.50_0.1_0_0_20240905/checkpoints/63
jobs:
- name: static_decision_threshold_tuning
  sim_path: /work1/Doutorado/data/3D/static/rocker-arm
  model_path: /work1/Doutorado/data/3D/static/kfold3_hdp=2.0/sparse_regionwise_approach/models/model_sparse_voxelized_fluid_cnn_v3_4_10000_1.50_0.1_0_0_20240905
  sim_config: sim_config_hdp=2.0.yaml
  model_config: model_config_v2.yaml
  predict_id: v3_4_10000_1.50_0.1_0_0_kfold3_no_coarse
  pred_dir: predictions/decision-threshold-tunning/{decision_threshold:.2f}
  tuning:
    type: decision_threshold
    start: 0.0
    stop: 1.05
    step: 0.05
