comparisons:
  - gt_config_file: /work1/voxel-fluid-net/data/3D/simulations/db_blocks_3d_big_res/gt_config.yaml
    pred_config_files:
      - /work1/voxel-fluid-net/data/3D/simulations/db_blocks_3d_big_res/sparse_regionwise_approach/predictions/pred_sparse_voxelized_fluid_cnn_v3_4_100000_1.50_0.10_0_2_kfold3/pred_config.yaml
      - /work1/voxel-fluid-net/data/3D/simulations/db_blocks_3d_big_res/sparse_regionwise_approach/predictions/pred_sparse_voxelized_fluid_cnn_v3_4_100000_1.50_0.10_0_2_kfold3_no_coarse/pred_config.yaml
  - gt_config_file: /work1/voxel-fluid-net/data/3D/simulations/ddb_3d_big_res/gt_config.yaml
    pred_config_files:
      - /work1/voxel-fluid-net/data/3D/simulations/ddb_3d_big_res/sparse_regionwise_approach/predictions/kfold3-tese/pred_sparse_voxelized_fluid_cnn_v3_4_100000_1.50_0.10_0_4_kfold3/pred_config.yaml
      - /work1/voxel-fluid-net/data/3D/simulations/ddb_3d_big_res/sparse_regionwise_approach/predictions/kfold3-tese/pred_sparse_voxelized_fluid_cnn_v3_4_100000_1.50_0.10_0_4_kfold3_no_coarse/pred_config.yaml
  - gt_config_file: /work1/voxel-fluid-net/data/3D/simulations/fountain_3d_big_res/gt_config.yaml
    pred_config_files:
      - /work1/voxel-fluid-net/data/3D/simulations/inlet_vortex_3d_big_res/sparse_regionwise_approach/predictions/kfold3/pred_sparse_voxelized_fluid_cnn_v3_4_100000_1.50_0.10_0_1_kfold3/pred_config.yaml
      - /work1/voxel-fluid-net/data/3D/simulations/inlet_vortex_3d_big_res/sparse_regionwise_approach/predictions/kfold3/pred_sparse_voxelized_fluid_cnn_v3_4_100000_1.50_0.10_0_1_kfold3_no_coarse/pred_config.yaml
  - gt_config_file: /work1/voxel-fluid-net/data/3D/simulations/inlet_collision_3d_big_res/gt_config.yaml  
    pred_config_files:
      - /work1/voxel-fluid-net/data/3D/simulations/inlet_collision_3d_big_res/sparse_regionwise_approach/predictions/kfold3/pred_sparse_voxelized_fluid_cnn_v3_4_100000_1.50_0.10_0_3_kfold3/pred_config.yaml
      - /work1/voxel-fluid-net/data/3D/simulations/inlet_collision_3d_big_res/sparse_regionwise_approach/predictions/kfold3/pred_sparse_voxelized_fluid_cnn_v3_4_100000_1.50_0.10_0_3_kfold3_no_coarse/pred_config.yaml
  - gt_config_file: /work1/voxel-fluid-net/data/3D/simulations/inlet_vortex_3d_big_res/gt_config.yaml
    pred_config_files:
      - /work1/voxel-fluid-net/data/3D/simulations/inlet_vortex_3d_big_res/sparse_regionwise_approach/predictions/kfold3/pred_sparse_voxelized_fluid_cnn_v3_4_100000_1.50_0.10_0_1_kfold3/pred_config.yaml
      - /work1/voxel-fluid-net/data/3D/simulations/inlet_vortex_3d_big_res/sparse_regionwise_approach/predictions/kfold3/pred_sparse_voxelized_fluid_cnn_v3_4_100000_1.50_0.10_0_1_kfold3_no_coarse/pred_config.yaml
report:
  output_path: ./reports/predictions_comparison_report
  format: csv
  plot_metrics: false
  print_metrics: true
