tensorflow:
  gpu_memory_growth: true
voxel_fluid:
  tasks:
    boundary:
      type: classification
      labels:
      - interior
      - boundary
      outputs: 2
    normal:
      type: regression
      outputs: 3
  features:
    occupancy: 1
  approach: sparse_regionwise
  search_radius: 1.5
  grid_length: 0.1
  enable_plot: false
  coarse_prediction: null
prediction:
  batch_size: 100000
  device: cuda
  initial_step: -1
  final_step: -1
  skip_steps: 1
  grid_offset: false
  resolution_based_on_mean_distance: true
  hdp: 1.73
  post_processing:
    extract_mesh: true
    poisson_recon_path: /work1/SurfaceReconstruction/AdaptiveSolvers/Bin/Linux/PoissonRecon
jobs:
- name: sparse_regionwise_boundary_normal
  sim_path: /work1/voxel-fluid-net/data/3D/big2/inlet_collision_3d_big_res
  model_path: /work1/voxel-fluid-net/models/kfold3/sparse_regionwise_approach/models/model_sparse_voxelized_fluid_cnn_v3_4_100000_1.50_0.10_0_3
  sim_config: sim_config.yaml
  model_config: model_config_v2.yaml
  predict_id: v3_4_100000_1.50_0.10_0_3_200626
  pred_dir: ./outputs
  skip_if_exists: false
